config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :monsters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/monster.rb
class Monster < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: %i[ show edit update destroy ]

  # GET /monsters or /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1 or /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters or /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to monster_url(@monster), notice: "Monster was successfully created." }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1 or /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to monster_url(@monster), notice: "Monster was successfully updated." }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1 or /monsters/1.json
  def destroy
    @monster.destroy

    respond_to do |format|
      format.html { redirect_to monsters_url, notice: "Monster was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monster_params
      params.require(:monster).permit(:name, :level, :habitat, :season, :materials, :dragonica, :hp, :mp, :initiative, :condition, :str, :dex, :int, :spi, :accuracy, :damage, :armor, :description, :specialability)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RyuutamaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/_form.html.erb
<%= form_with(model: monster) do |form| %>
  <% if monster.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
        <% monster.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :level, style: "display: block" %>
    <%= form.number_field :level %>
  </div>

  <div>
    <%= form.label :habitat, style: "display: block" %>
    <%= form.text_field :habitat %>
  </div>

  <div>
    <%= form.label :season, style: "display: block" %>
    <%= form.text_field :season %>
  </div>

  <div>
    <%= form.label :materials, style: "display: block" %>
    <%= form.text_field :materials %>
  </div>

  <div>
    <%= form.label :dragonica, style: "display: block" %>
    <%= form.number_field :dragonica %>
  </div>

  <div>
    <%= form.label :hp, style: "display: block" %>
    <%= form.number_field :hp %>
  </div>

  <div>
    <%= form.label :mp, style: "display: block" %>
    <%= form.number_field :mp %>
  </div>

  <div>
    <%= form.label :initiative, style: "display: block" %>
    <%= form.number_field :initiative %>
  </div>

  <div>
    <%= form.label :condition, style: "display: block" %>
    <%= form.number_field :condition %>
  </div>

  <div>
    <%= form.label :str, style: "display: block" %>
    <%= form.number_field :str %>
  </div>

  <div>
    <%= form.label :dex, style: "display: block" %>
    <%= form.number_field :dex %>
  </div>

  <div>
    <%= form.label :int, style: "display: block" %>
    <%= form.number_field :int %>
  </div>

  <div>
    <%= form.label :spi, style: "display: block" %>
    <%= form.number_field :spi %>
  </div>

  <div>
    <%= form.label :accuracy, style: "display: block" %>
    <%= form.text_field :accuracy %>
  </div>

  <div>
    <%= form.label :damage, style: "display: block" %>
    <%= form.text_field :damage %>
  </div>

  <div>
    <%= form.label :armor, style: "display: block" %>
    <%= form.number_field :armor %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :specialability, style: "display: block" %>
    <%= form.text_area :specialability %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/monsters/_monster.html.erb
<div id="<%= dom_id monster %>">
  <p>
    <strong>Name:</strong>
    <%= monster.name %>
  </p>

  <p>
    <strong>Level:</strong>
    <%= monster.level %>
  </p>

  <p>
    <strong>Habitat:</strong>
    <%= monster.habitat %>
  </p>

  <p>
    <strong>Season:</strong>
    <%= monster.season %>
  </p>

  <p>
    <strong>Materials:</strong>
    <%= monster.materials %>
  </p>

  <p>
    <strong>Dragonica:</strong>
    <%= monster.dragonica %>
  </p>

  <p>
    <strong>Hp:</strong>
    <%= monster.hp %>
  </p>

  <p>
    <strong>Mp:</strong>
    <%= monster.mp %>
  </p>

  <p>
    <strong>Initiative:</strong>
    <%= monster.initiative %>
  </p>

  <p>
    <strong>Condition:</strong>
    <%= monster.condition %>
  </p>

  <p>
    <strong>Str:</strong>
    <%= monster.str %>
  </p>

  <p>
    <strong>Dex:</strong>
    <%= monster.dex %>
  </p>

  <p>
    <strong>Int:</strong>
    <%= monster.int %>
  </p>

  <p>
    <strong>Spi:</strong>
    <%= monster.spi %>
  </p>

  <p>
    <strong>Accuracy:</strong>
    <%= monster.accuracy %>
  </p>

  <p>
    <strong>Damage:</strong>
    <%= monster.damage %>
  </p>

  <p>
    <strong>Armor:</strong>
    <%= monster.armor %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= monster.description %>
  </p>

  <p>
    <strong>Specialability:</strong>
    <%= monster.specialability %>
  </p>

</div>

app/views/monsters/edit.html.erb
<h1>Editing monster</h1>

<%= render "form", monster: @monster %>

<br>

<div>
  <%= link_to "Show this monster", @monster %> |
  <%= link_to "Back to monsters", monsters_path %>
</div>

app/views/monsters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Monsters</h1>

<div id="monsters">
  <% @monsters.each do |monster| %>
    <%= render monster %>
    <p>
      <%= link_to "Show this monster", monster %>
    </p>
  <% end %>
</div>

<%= link_to "New monster", new_monster_path %>

app/views/monsters/new.html.erb
<h1>New monster</h1>

<%= render "form", monster: @monster %>

<br>

<div>
  <%= link_to "Back to monsters", monsters_path %>
</div>

app/views/monsters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @monster %>

<div>
  <%= link_to "Edit this monster", edit_monster_path(@monster) %> |
  <%= link_to "Back to monsters", monsters_path %>

  <%= button_to "Destroy this monster", @monster, method: :delete %>
</div>